services:
  postgres:
    image: postgres:16
    container_name: weather_postgres
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
    ports:
      - "5432:5432"
    volumes:
      - ./pg/data:/var/lib/postgresql/data
      - ./pg/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - elt_network

  af:
    container_name: airflow_container
    image: apache/airflow:3.0.0
    ports:
      - 8000:8080
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://weather_user:weather_pass@postgres:5432/weather_db
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - postgres
    networks:
      - elt_network
    command: >
      bash -c "airflow db migrate && airflow standalone"


  dbt:
    container_name: weather_dbt 
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./weather_dbt:/usr/app
      - ./dbt_profiles:/root/.dbt
    depends_on:
      - postgres
    networks:
      - elt_network
    command: run

volumes:
  pg_data:

networks:
  elt_network:
    driver: bridge
