version: 2

models:
  - name: weather_data
    description: "Contains historical weather information from the API"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - not_null
          - unique
      - name: date
        description: "Date of the weather data"
        tests:
          - not_null
      - name: location
        description: "Location of the weather data"
      - name: temp_c
        description: "Temperature in Celsius"
      - name: humidity
        description: "Humidity percentage"
      - name: precip_mm
        description: "Precipitation in mm"
      - name: wind_kph
        description: "Wind speed in km/h"
      - name: api_timestamp
        description: "Time the data was fetched"
        tests:
          - not_null

  - name: sales_data
    description: "Contains historical sales data"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - not_null
          - unique
      - name: date
        description: "Date of the sale"
        tests:
          - not_null
      - name: store_id
        description: "ID of the store"
      - name: umbrellas
        description: "Units of umbrellas sold"
      - name: cold_drinks
        description: "Units of cold drinks sold"
